feat(New hiseqx validation functions)
Clinical-Genomics/demultiplexing pull request #112
Opened 2020-10-27 14:37 UTC by karlnyr

This PR adds new functions in validation of hiseqx SampleSheet. Specifically, they check wether there are more than type of indexes present(i.e., single or dual indexes) as well as an implementation of a sanity length check on dual indexes 

**How to prepare for test**:
- [ ] ssh to hasta
- [ ] install on stage:
`bash servers/resources/hasta.scilifelab.se/update-demux-stage.sh feat/hiseq-samplesheet-validation`

**How to test**:
- [ ] login to thalamus
- [ ] do one samplesheet with multiple types of indexes
- [ ] do one samplesheet with dual indexes of variable length
- [ ] run demux sheet validate --application wgs <sample_sheet_here>

**Expected test outcome**:
- [ ] Faulty SampleSheet raises their expected errors 
- [ ] Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

2021-01-07 13:21 UTC, henrikstranneheim commented
@karlnyr What is the status of this one?

2021-01-09 15:58 UTC, karlnyr commented
> @karlnyr What is the status of this one?

I've written most of the tests already but got interrupted with production during Christmas. I Will most likely pick this up again next week 👍

2021-01-19 09:44 UTC, karlnyr commented
I mixed up this PR and another one. I have now finished up the function and added a test for the function. The function is to be used in the demultiplexing workflow of hiseqx, so testing on hasta could be performed to test it.

2021-06-04 13:11 UTC, karlnyr commented
Samplesheet with multiple index types:
![image](https://user-images.githubusercontent.com/45558267/120806297-fa245600-c546-11eb-9365-0ffd39f08102.png)

Test:
![image](https://user-images.githubusercontent.com/45558267/120806377-12947080-c547-11eb-9e1c-2c6747a10e02.png)

Samplesheet with variable dual index length:
![image](https://user-images.githubusercontent.com/45558267/120805900-8f731a80-c546-11eb-92e1-e2268c0b75d5.png)

Test:
![image](https://user-images.githubusercontent.com/45558267/120806069-b3366080-c546-11eb-9e7d-28be15634233.png)

2021-06-04 13:12 UTC, karlnyr commented
@barrystokman here it is

@henrikstranneheim only 5 months later after your first ping on the repo 👍

2021-06-08 08:36 UTC, karlnyr commented
@barrystokman can you give me a review just to make it official? You may have already looked through the code but.... for appearance sake 💯

2021-06-08 09:05 UTC, barrystokman requested changes
Looks good, just had some minor remarks.

2021-06-08 09:07 UTC, barrystokman commented
Let's decide what to do with the 2500 tests since I'm doing those in my PR as well.

2021-06-08 09:36 UTC, karlnyr commented on demux/utils/samplesheet.py
> +    sample_sheet.validate()
hehe, oopsie 😅

2021-06-09 05:34 UTC, barrystokman requested changes
You removed stuff that was supposed to be in there, things I added in my PR. Maybe it's best to revert some of the merge stuff.

2021-06-09 05:34 UTC, barrystokman commented on demux/utils/samplesheet.py
> +class SampleSheetParsexception(Exception):
```suggestion
class SampleSheetParseException(Exception):
```

2021-06-09 05:34 UTC, barrystokman commented on demux/utils/samplesheet.py
> +        Should be instancied with the samplesheet path as an argument.
```suggestion
        Should be instantiated with the samplesheet path as an argument.
```

2021-06-09 05:34 UTC, barrystokman commented on demux/utils/samplesheet.py
> +            raise SampleSheetParsexception("No data found!")
```suggestion
            raise SampleSheetParseException("No data found!")
```

2021-06-09 05:34 UTC, barrystokman commented on demux/utils/samplesheet.py
> +        """ Return True if lane contains multiple samples based on the orignal header """
```suggestion
        """ Return True if lane contains multiple samples based on the original header """
```

2021-06-09 05:34 UTC, barrystokman commented on demux/utils/samplesheet.py
> +        def _validate_uniq_index(samplesheet):
```suggestion
        def _validate_unique_index(samplesheet):
```

2021-06-09 05:34 UTC, barrystokman commented on demux/utils/samplesheet.py
> -                            samples_list.sort()
This was in my PR and need to be in place. You removed stuff that was supposed to be in there!

2021-06-09 05:34 UTC, barrystokman commented on demux/utils/samplesheet.py
> -                                    " , ".join(samples_list), lane
Please leave this in.

2021-06-09 05:34 UTC, barrystokman commented on demux/utils/samplesheet.py
> +        rs = _validate_uniq_index(self.samplesheet)
```suggestion
        rs = _validate_unique_index(self.samplesheet)
```

Maybe it's best to revert some stuff, this was all put in by me, very much intentionally.

2021-06-09 05:34 UTC, barrystokman commented on tests/conftest.py
> +@pytest.fixture(name="x_samplesheet_wrong_font_path")
"wrong font" was a joke

2021-06-09 05:34 UTC, barrystokman commented on tests/conftest.py
> +@pytest.yield_fixture(scope="function", name="novaseq_runparameters_api")
this needs to be put back

2021-06-09 14:07 UTC, karlnyr commented
@barrystokman I think I finally solved it all. After reverting, messing up merging 60+ times and pushing I think I finally managed to get the master into this branch. Can you please double check and then I will merge this and get on with the next PR

2021-06-10 05:28 UTC, barrystokman approved these changes
🏁

2021-06-10 05:44 UTC, merged

2021-06-10 06:07 UTC, henrikstranneheim commented
Well done! 🎉